<?php
echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "<head>\n";
echo "	<meta charset=\"utf-8\">\n";
echo "	<title>Tomi's | WELCOME</title>\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\n";
echo "	<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\n";
echo "</head>\n";
echo "<body>\n";
echo "	<header>\n";
echo "	<div class=\"container\">\n";
echo "	<div id=\"brand\">\n";
echo "	<h1><span class=\"highlight\">TOMILOLA</span> OGUNDIRAN</h1>\n";
echo "	</div>\n";
echo "	<nav>\n";
echo "	<ul>\n";
echo "		<li class=\"current\"> </li>\n";
echo "		<li><a href=\"#RESUME\"></a></li>\n";
echo "		<li><a href=\"CONTACT\"></a></li>\n";
echo "	</ul>\n";
echo "	</nav>\n";
echo "	</div>\n";
echo "	</header>\n";
echo "	<section id=\"showcase\">\n";
echo "	<div class=\"container\">\n";
echo "		<marquee behavior=\"slide\" direction=\"left\">\n";
echo "		<p>\"Today <strong>YOU</strong> are <strong>You</strong>, that is <strong>TRUER</strong> than <strong>TRUE</strong>, there is <strong>NO ONE</strong> alive who is <strong>YOUER</strong> than <strong>YOU</strong>.\"</p>		\n";
echo "		<p>~ Dr Seuss ~		</p>\n";
echo "		</marquee>\n";
echo "	</div>\n";
echo "	</section>\n";
echo "	<section id=\"about\">\n";
echo "	<div class=\"container\">\n";
echo "		<h2>ABOUT ME</h2>\n";
echo "		<p>My name is Oluwatomilola Ogundiran. I have a basic understanding of Information Systems and Technologies. I am open to new system development skills and technologies. I enjoy working as a member of teams, where I will garner more experience and skills that will enable me to contribute positively to achievement of set goals and objectives.</p>\n";
echo "	</div>\n";
echo "	</section>\n";
echo "	<section id=\"boxes\">\n";
echo "	<div class=\"container\">\n";
echo "		<h2>RESUME</h2>\n";
echo "		<p>Click <a href= \"https://www.scribd.com/document/356615200/CV-Tomilola-Ogundiran-2017\"> here </a> to view my resume</p>\n";
echo "		<div class=\"box\">\n";
echo "			<i class=\"fa fa-thumbs-up\" aria-hidden=\"true\" style = \"font-size: 40px;\"></i>\n";
echo "			<h4>SKILLS</h4>\n";
echo "			<p>C, C++</p>\n";
echo "			<p>Java</p>\n";
echo "			<p>Python</p>\n";
echo "			<p>JSP</p>\n";
echo "			<p>HTML, CSS</p>\n";
echo "			<p>PHP</p>\n";
echo "		</div>\n";
echo "		<div class=\"box\">\n";
echo "			<i class=\"fa fa-graduation-cap\" aria-hidden=\"true\" style = \"font-size: 40px;\"></i>\n";
echo "			<h4>EDUCATION</h4>\n";
echo "			<p>Covenant University, Ota, Ogun State\n";
echo "			B Sc Computer Science  \n";
echo "			Second Class Upper</p>\n";
echo "			<p>Lagos Anglican Girls’ Grammar School, Surulere, Lagos state\n";
echo "			WASSCE </p>\n";
echo "			<p>The Redeemed Cornerstone School, Sogunle, Lagos State</p>\n";
echo "		</div>\n";
echo "		<div class=\"box\">\n";
echo "			<i class=\"fa fa-trophy\" aria-hidden=\"true\" style = \"font-size: 40px;\"></i>\n";
echo "			<h4>ACTIVITIES</h4>\n";
echo "			<p>IBM Application Security Analyst February 2017</p>\n";
echo "			<p>GDG Covenant University</p>\n";
echo "			<p>Bishop Akinde Science Fair</p>\n";
echo "			<p>Fun City Academic Honor Roll </p>\n";
echo "			<p>Women Techmakers</p>\n";
echo "		</div>\n";
echo "		<div class=\"box\">\n";
echo "			<i class=\"fa fa-heart\" aria-hidden=\"true\" style = \"font-size: 30px;\"></i>\n";
echo "			<h4>INTERESTS</h4>\n";
echo "			<p>Cooking</p>\n";
echo "			<p>Travelling</p>\n";
echo "			<p>Music</p>\n";
echo "			<p>Children</p>\n";
echo "		</div>\n";
echo "	</div>\n";
echo "	</section>\n";
echo "	<section id=\"contact\">\n";
echo "	<div class=\"container\">\n";
echo "		<h2>CONTACT</h2>\n";
echo "		<p>If you are interested in speaking to me, please contact me.</p>\n";
echo "		<i class=\"fa fa-mobile\" aria-hidden=\"true\" style = \"font-size: 40px;\"></i>\n";
echo "		 <p> <span class=\"highlight\"> 08033044319 </span> </p>\n";
echo "		<a href=\"https://www.facebook.com/tomilola.ogundiran\"><i class=\"fa fa-facebook-square\" aria-hidden=\"true\" style = \"font-size: 40px;\"></i></a>\n";
echo "		<a href=\"https://www.instagram.com/thetomilola/\"><i class=\"fa fa-instagram\" aria-hidden=\"true\" style = \"font-size: 40px;\"></i></a>\n";
echo "		<a href=\"\"><i class=\"fa fa-google-plus-square\" aria-hidden=\"true\" style = \"font-size: 40px;\"></i></a>\n";
echo "		<a href=\"https://twitter.com/thetomilola\"><i class=\"fa fa-twitter-square\" aria-hidden=\"true\" style = \"font-size: 40px;\"></i></a>\n";
echo "		<a href=\"https://www.linkedin.com/\"><i class=\"fa fa-linkedin-square\" aria-hidden=\"true\" style = \"font-size: 40px;\"></i></a>\n";
echo "	</div>\n";
echo "	</section>\n";
echo "<footer>\n";
echo "	<p>Tomi Ogundiran, Copyright &copy; 2017</p>\n";
echo "</footer>\n";
echo "\n";
echo "</body>\n";
echo "</html>\n";
?>